### ISSUE TITLE
Card system

### ISSUE THREAD

**Issue by ShcherbaDev** [Minez0r/Discord-Bot#1]
Надо сделать фичу, как в боте "dank memer"
Если пользователь пишет `.проф`, то бот ответит картинкой:
![типа так](https://cdn.discordapp.com/attachments/695232967722795022/695267127661166662/profile.png)

Я займусь этим, ок да?

**Comment by FeadenGlow** [comment]
Ну лан, разрешаю

**Comment by ShcherbaDev** [comment]
Добавлено в f026cbb6a09c174675eee71bca6730e5db5d29be
