### ISSUE TITLE
Продвинутые заметки

### ISSUE THREAD

**Issue by FeadenGlow** [Minez0r/Discord-Bot#3]
Требуется сделать помимо заметок команду .темы боту, вот пример как это должно работать:

Сделать продвинутые заметки
<------------------->
С возможностью записи тем, описаний через абзац да и вообще возможностью поставить возле неё пропуск(⬜), крест(❌) и галочку (✅)
Заметки должны выглядеть подобным образом:

.темы
1. ✅  переименовать золотую кирку в хлипкую
(<номер темы> <пропуск/крест/галка> <тема в строчку>) 

.темы 1
Переименовать золотую кирку в хлипкую
<------------------->
(<пропуск/крест/галка> <тема в строчку>
<------------------->
<описания>)

**Comment by ShcherbaDev** [comment]
Я могу знятся этим
